// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  text_block: dynamic(() => import("./TextBlock")),
  year_show_slice: dynamic(() => import("./YearShowSlice")),
};
